### PR TITLE
added aspect ratio parameter for graphs

### PR DESCRIPTION
**Pull request by woodworker**
i added a parameter for an aspectRatio for when someone does not want a 1:1 graph

maybe interesting for:
- https://github.com/pyrochlore/obsidian-tracker/issues/34
- https://github.com/pyrochlore/obsidian-tracker/issues/219
- https://github.com/pyrochlore/obsidian-tracker/issues/190

Example Picture:
grafik

### CODE REVIEW

**Comment by geezbert** [comment]
@woodworker Looks amazing - exactly what I was looking for, thanks! However I'm not much of a coder or versed in this realm. Is there any way of downloading the main.js, etc. files (the ones I gotta replace in my obsidian plugin folder) with this branch or modifications included? Seems like I can only download those in the "Releases" venue, because under the "src" File folder, I only see ".ts" files..

**Comment by woodworker** [comment]
i created a "pre-release" in my fork that contains these changes - https://github.com/woodworker/obsidian-tracker/releases/tag/v1.10.9-aspect-ratio

just download the zipfile it contains the needed main.js

**Comment by geezbert** [comment]
@woodworker works like a charm! thanks!

**Comment by lazyguru** [comment]
@woodworker thank you for your contribution

**Comment by lazyguru** [comment]
FYI this has just now been released (sorry for the delay between merge and release, I thought I might have something else to add to the release but decided it was better to release this as-is to get it out there). Again, thank you for your contribution!

**Pull request merged**
