### PR TITLE
Support for inline dataview fields

### PR DESCRIPTION
**Pull request by Laharah**
Add a collectDataFromInlineDvField.

I was originally going to just add the bracket/paren matching to the original regex, but it got nasty quickly. Anyone who's got good regex-fu is welcome to try it themselves. Either way this code now matches both [inline::style] and (hiddenKey::style) dataview metas.

### CODE REVIEW

**Comment by tcpsyn** [comment]
Thanks for that.

**Comment by solpyro** [comment]
Looking at the regex here #108 it seems like we could get away with just modifying the original regex in  `collectDataFromDvField`, rather than having to run two near identical searches across the search space.

Had you tried this approach?
```regex
-------vvv   Allows for a pipe to start the match, in case of a closely wrapped table

(^| |\t|\|)(\[|\()?\*{0,2}dvTarget\*{0,2}(::[ |\t]*(?<value>[\d\.\/\-\w,@; \t:]*)(\]|\))?)

-----------^^^^^^^^------   Allows for optional [ or ( and closing ) or ]   -----^^^^^^^^
```
[regex101](https://regex101.com/r/KnsKYL/1) shows that this search matches everything from my test set at least

**Comment by lazyguru** [comment]
Hi, I now have write access and have been going through all open PRs to get them merged. This is the last of the "overdue" PRs for processing. I see some comments with feedback on the changes here. Are there any updates to be made here?

**Comment by Laharah** [comment]
It works as is, but as @solpyro pointed out, it's not very efficient. I'm going to do some testing on his solution in the next couple of days, so I'd consider this PR open until I can take a look.

**Comment by Laharah** [comment]
Okay, rebased on master, updated the regex, and implemented some tests in the example vault. This PR is ready to go!

**Comment by lazyguru** [comment]
I haven't forgotten about this. I just need to run through a bit of testing before merging and publishing. Give me a few more days

**Comment by lazyguru** [comment]
Thank you for your contribution!

**Pull request merged**
